---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pricing-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pricing-api
  template:
    metadata:
      labels:
        app: pricing-api
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: app
          image: us.gcr.io/rightscale.com/services1/cloud-pricing-api:0.2
          ports:
            - containerPort: 4000
          env:
            - name: MONGO_URL
              value: mongodb://mongo-0.mongo:27017,mongo-1.mongo:27017,mongo-2.mongo:27017/cloudPricing?replicaSet=rs0
            - name: MONGO_URI
              value: mongodb://mongo-0.mongo:27017,mongo-1.mongo:27017,mongo-2.mongo:27017/cloudPricing?replicaSet=rs0
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: pricing-api
spec:
  selector:
    app: pricing-api
  ports:
    - port: 80
      targetPort: 4000
  type: LoadBalancer
