---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pricing-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pricing-api
  template:
    metadata:
      labels:
        app: pricing-api
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: app
          image: us.gcr.io/rightscale.com/services1/cloud-pricing-api:latest
          ports:
            - containerPort: 4000
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: pricing-api
spec:
  selector:
    app: pricing-api
  ports:
    - port: 80
      targetPort: 4000
  type: LoadBalancer
