---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pricing-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pricing-api
  template:
    metadata:
      labels:
        app: pricing-api
    spec:
      containers:
        - name: app
          image: rshade/cloud-pricing-api
          ports:
            - containerPort: 4000
          env:
            - name: MONGO_URL
              value: mongodb://mongo-0.mongo,mongo-1.mongo,mongo-2.mongo:27017/cloudPricing
            - name: MONGO_URI
              value: mongodb://mongo-0.mongo,mongo-1.mongo,mongo-2.mongo:27017/cloudPricing
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: pricing-api
spec:
  selector:
    app: pricing-api
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer